docs/layouts/partials/icons.html
@mdo I personally find this annoying with the current layout. Especially on smaller devices...
=> docs: remove autofocus

package.json
Change "Bootstra" to "Bootstrap"
=> Fix package.json description misspelling

config.yml
=> Change navbar GitHub link to org

docs/layouts/partials/social.html
=> Fix social meta tags title for homepage

.eslintrc.json, build/build-pages.js, package.json
_This isn't the best work I've done, but it's a start that I'm damned proud of lol. And it works! 😄 _
This PR adds a script that loops through the `icons/` directory, checks for an existing associated permalink page in `docs/content/icons/`, and if one does not exist, then creates said file with a front matter template. I know nothing about writing JS still, so this was pieced together with countless Googling and what not, so all feedback is welcome.
---
**Reference art:**
- https://stackoverflow.com/questions/32511789/looping-through-files-in-a-folder-node-js/32511953
- https://stackoverflow.com/questions/31195391/create-a-file-if-it-doesnt-already-exist
- https://nodejs.dev/writing-files-with-nodejs
=> Add script to create permalink pages

docs/assets/scss/_clipboard-js.scss, docs/assets/scss/_variables.scss, docs/layouts/icons/single.html
- Adjusts columns and padding so smallest icon doesn't disappear
- Adjusts button styling on copy button to be more obvious
- Adds heading to give some separation and a CTA of sorts to the html source code
Fixes #255.
=> Improve icons layout

.github/workflows/deploy.yml, .github/workflows/test.yml
* update to `actions/cache@v2`
* remove the yml file from cache invalidation
=> Action updates

README.md, config.yml, package-lock.json, package.json
- Update version in config and npm files
- Update link to Figma file
Additional todos:
=> Prep for Alpha 5

.browserslistrc
Still need to finish the upstream patch https://github.com/twbs/bootstrap/pull/30986, so currently it backports the upstream main branch changes.
=> Update .browserslistrc from upstream

README.md, config.yml, package.json
- Update version in package.json and config
- Update link to new Figma file with full Figma components and latest changes
- Update screenshot and count in readme
=> Prep for v1 stable release

package.json
After merging this, might be worth publishing a v1.2.1 @mdo.
=> package.json: Fix font folder name

build/build-svgs.js
* rename a few variables
* cache variable
Split from #575
=> build-svgs.js: minor tweaks

build/build-svgs.js
Trying to fix #50. Still needs work because I have to use `process.exit(1)` in the IIFE (formerly `main()`)
~~Requires #575 and will need a rebase after #602~~
Non-whitespace diff: https://github.com/twbs/icons/pull/603/files?w=1
=> build-svgs.js: switch to async/await and tweaks

build/build-pages.js, build/build-svgs.js
Apparently, there's no need to reject the promise
=> Update build scripts

docs/layouts/icons/single.html
=> docs: fix breadcrumb markup

docs/content/icons/exclamation-circle-fill.md, docs/content/icons/exclamation-circle.md, docs/content/icons/exclamation-octagon-fill.md, docs/content/icons/exclamation-octagon.md, docs/content/icons/exclamation-square-fill.md, docs/content/icons/exclamation-square.md, docs/content/icons/exclamation-triangle-fill.md, docs/content/icons/exclamation-triangle.md
Not sure if there are more, I'll double check later by comparing the built HTML.
=> docs: fix titles

build/vnu-jar.js
So that it works with directories with spaces
=> vnu-jar: quote vnu's path

docs/layouts/icons/single.html, docs/layouts/partials/icons.html, docs/layouts/partials/scripts.html
Preview: https://deploy-preview-750--bootstrap-icons.netlify.app/
=> docs: take categories into consideration too

docs/content/_index.md
Sorry to be a pedant but this confused me slightly and then I realised it was a typo. So I thought I'd submit a fix :) Yay for icons and keep up the great work!
=> Fixed teeny typo (who -> how)

docs/content/_index.md
=> Add note about `<use>` in Chrome

docs/assets/scss/docs.scss, docs/layouts/icons/single.html
Follow-up to #823. /cc @XhmikosR
=> Fix single view icon examples

README.md, config.yml, docs/layouts/partials/analytics.html, package-lock.json, package.json
- Bumps versions everywhere
- Updates Figma link (now for the first time as a Community link)
=> Prep for v1.5.0

.github/dependabot.yml
@mdo should we change it to monthly too?
=> Change dependabot to run monthly

package.json
=> Rename local npm publish script to release

docs/assets/scss/docs.scss, docs/layouts/partials/stylesheet.html
We can revisit this later if it hurts performance.
=> docs: include the built font CSS

docs/assets/js/application.js
=> Disable enter key on icon search

docs/content/icons/arrow-clockwise.md, docs/content/icons/arrow-counterclockwise.md
See https://github.com/twbs/icons/issues/909#issuecomment-1017061661
=> add undo/redo tags to clockwise arrows

docs/content/_index.md
=> extend accessibility section

docs/content/icons/arrow-repeat.md
[Name used by Font Awesome 5](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=sync)
Fixes #1208
=> Add sync tag to arrow-repeat

.github/workflows/test.yml, package-lock.json, package.json
This results to -87 dev packages.
@mdo: are you OK with this?
=> Move linkinator to actions

build/build-svgs.js, package-lock.json, package.json, svgo.config.js
Fixes #1049.
The svgo plugin is based on the default plugin [addAttributesToSVGElement](https://github.com/svg/svgo/blob/master/plugins/addAttributesToSVGElement.js).
CC: @XhmikosR
=> Use a custom svgo plugin to optimize svg attributes

build/font/css.hbs
=> Add `font-display: block`

build/font/scss.hbs, font/bootstrap-icons.scss
=> Update font Sass for more control over paths

docs/content/icons/airplane-engines-fill.md, docs/content/icons/airplane-engines.md, docs/content/icons/airplane-fill.md, docs/content/icons/airplane.md
This pull request adds the "aircraft" tag to all airplane icons.
=> Add "aircraft" tag to airplane icons

build/font/scss.hbs, config.yml, package-lock.json, package.json
Some behind the scenes updates for dependencies, plus dark mode! Also fixes an inconsistency in the hash.
=> Ship v1.10.3

package-lock.json, package.json
This version is using my @xhmikosr/bin-wrapper fork. All current npm vulnerabilities are fixed.
=> Update hugo-bin to v0.100.0

docs/layouts/_default/sprite.html
=> sprite.html: fix wrong breadcrumb

LICENSE.md, build/font/css.hbs, build/font/scss.hbs
=> font: add license header

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml, config.yml, docs/assets/js/vendor/list.js, docs/layouts/partials/scripts.html, package-lock.json, package.json
Fixes #895
Preview: https://deploy-preview-1651--bootstrap-icons.netlify.app/
=> Work around list.js not working with hyphens

docs/assets/js/list.js
- searchDelay: 250
- indexAsync: true
=> docs: specify `searchDelay: 250` for list.js

config.yml, docs/layouts/partials/scripts.html
=> config.yml: mount bootstrap.bundle.min.js in static folder

docs/assets/js/color-modes.js
This PR gathers `color-modes.js` recent modifications from Bootstrap:
- https://github.com/twbs/bootstrap/commit/f0be063c9792f6fd123d933335efd0d8cc7f6f1f
- https://github.com/twbs/bootstrap/commit/ad9cb223a9899093e2537fdca6222e36465080a2
=> Improve color modes JS

.github/workflows/deploy.yml
=> Deploy: upload bootstrap icons zip

.github/workflows/deploy.yml
=> Revert "Deploy: upload bootstrap icons zip"

package-lock.json, package.json
Fixes #1852 
xmldom > v0.8.8 breaks svg-sprite, should be reported in xmldom, but time...
=> Fix svg sprite

docs/content/_index.md
=> Fix Broken link in usage instructions

docs/assets/js/search.js
=> docs: update search

docs/assets/js/color-modes.js
This PR simply applies the fix provided upstream in https://github.com/twbs/bootstrap/pull/39224
=> Fix edge case in `color-modes.js`

docs/content/_index.md
=> Update usage docs for Vite and Parcel relative path issues
